version: 0.0

os: linux

files:
  - source: /scripts
    destination: /var/www/appointment

hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
      permissions: +x

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: root
      permissions: +x
