---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: vaccination-system-dev
  labels:
    svc: vms
spec:
  type: ClusterIP
  selector:
    vms: auth
  ports:
  - name: web
    protocol: TCP
    port: 8002
    targetPort: 19090
